routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get( '/home', 'HomeController@index' )->middleware( [ '\App\Http\Middleware\CheckAdmin' ] )->name( 'home' );

Route::get( '/db_backup', 'AdminsController@download_backup' )->middleware( [ '\App\Http\Middleware\CheckAdmin' ] )->name( 'db_backup' );
Route::get( '/db_partial_backup_csv', 'AdminsController@download_partial_backup_csv' )->middleware( [ '\App\Http\Middleware\CheckAdmin' ] )->name( 'db_partial_backup_csv' );


Route::group(
    [
        'prefix'    => 'users',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( 'administrators', 'UsersController@administrators' )->name( 'administrators' );
        Route::get( 'customers', 'UsersController@customers' )->name( 'customers' );
        Route::post( 'customers', 'UsersController@customersearch' )->name( 'customers-search' );
        Route::get( 'supervisors', 'UsersController@supervisors' )->name( 'supervisors' );
        Route::get( 'shop-owners', 'UsersController@commerciants' )->name( 'shop-owners' );
        Route::post( 'shop-owners', 'UsersController@commerciantsearch' )->name( 'commerciants-search' );
        Route::get( 'details/{id}', 'UsersController@details' )->name( 'user-details' );
        Route::get( 'status/{id}/{status}', 'UsersController@status' )->name( 'user-status' );
        Route::get( 'confirmed/{id}/{confirmed}', 'UsersController@confirmed' )->name( 'user-confirmed' );
        Route::get( 'delete-customer/{id}', 'UsersController@deleteCustomer' )->name( 'delete-customer' );
    }
);

Route::group(
    [
        'prefix'    => 'customers',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( 'favs/{id}', 'CustomersController@customerFavs' )->name( 'customer-favs' );
        Route::get( 'edit/{id}', 'CustomersController@edit' )->name( 'edit-customer' );
        Route::post( 'update', 'CustomersController@update' )->name( 'update-customer' );
        Route::get( 'export', 'CustomersController@export' )->name( 'export-customers' );
    }
);

Route::group(
    [
        'prefix'    => 'shop-owners',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( 'edit/{id}', 'CommerciantsController@edit' )->name( 'edit-shop-owner' );
        Route::post( 'update', 'CommerciantsController@update' )->name( 'update-shop-owner' );
        Route::get( 'offers-trade/{id}', 'CommerciantsController@offersTrade' )->name( 'offers-trade' );
        Route::post( 'offers-trade-save/', 'CommerciantsController@offersTradeSave' )->name( 'offers-trade-save' );
        Route::get( 'delete-all-data/{id}', 'CommerciantsController@deleteAllData' )->name( 'delete-shop-owner-data' );
        Route::get( 'export', 'CommerciantsController@export' )->name( 'export-shop-owner' );

    }
);

Route::group(
    [
        'prefix'    => 'supervisors',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( 'new', 'SupervisorsController@new' )->name( 'add-supervisor' );
        Route::post( 'create', 'SupervisorsController@create' )->name( 'create-supervisor' );
        Route::get( 'edit/{id}', 'SupervisorsController@edit' )->name( 'edit-supervisor' );
        Route::post( 'update', 'SupervisorsController@update' )->name( 'update-supervisor' );
        Route::get( 'remove-from-mall/{id}', 'SupervisorsController@removeFromMall' )->name( 'remove-from-mall' );
        Route::get( 'delete-all-data/{id}', 'SupervisorsController@deleteAllData' )->name( 'delete-supervisor-data' );
    }
);

Route::group(
    [
        'prefix'    => 'admins',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( 'new', 'AdminsController@new' )->name( 'add-admin' );
        Route::post( 'create', 'AdminsController@create' )->name( 'create-admin' );
        Route::get( 'edit/{id}', 'AdminsController@edit' )->name( 'edit-admin' );
        Route::post( 'update', 'AdminsController@update' )->name( 'update-admin' );

    }
);

Route::group(
    [
        'prefix'    => 'shops',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( '', 'ShopsController@index' )->name( 'all-shops' );
        Route::get( 'malls/{id}', 'ShopsController@catenacommerciale' )->name( 'all-shops-catenacommerciale' );
        Route::get( 'ccenters/{id}', 'ShopsController@centrocommerciale' )->name( 'all-shops-centrocommerciale' );
        Route::get( 'details/{id}', 'ShopsController@details' )->name( 'shop-details' );
        Route::get( 'status/{id}/{status}', 'ShopsController@status' )->name( 'shop-status' );
        Route::get( 'edit/{id}', 'ShopsController@edit' )->name( 'edit-shop' );
        Route::post( 'update', 'ShopsController@update' )->name( 'update-shop' );
        Route::get( 'offers/{id}', 'ShopsController@offers' )->name( 'shop-offers' );
        Route::get( 'export', 'ShopsController@export' )->name( 'export-shops' );

        Route::get( 'new', 'ShopsController@new' )->name( 'add-shop' );
        Route::post( 'create', 'ShopsController@create' )->name( 'create-shop' );

        Route::get( 'upload-image/{id}', 'ShopsController@uploadImage' )->name( 'shop-upload-image' );
        Route::post( 'save-image', 'ShopsController@saveImage' )->name( 'shop-save-image' );

        Route::get( 'delete-all-data/{id}', 'ShopsController@deleteAllData' )->name( 'delete-shop-data' );
    }
);

Route::group(
    [
        'prefix'    => 'malls', //CATENE COMMERCIALI
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( '', 'MallsController@index' )->name( 'all-malls' );
        Route::get( 'details/{id}', 'MallsController@details' )->name( 'mall-details' );
        Route::get( 'edit/{id}', 'MallsController@edit' )->name( 'edit-mall' );
        Route::get( 'delete/{id}', 'MallsController@delete' )->name( 'delete-mall' );
        Route::post( 'update', 'MallsController@update' )->name( 'update-mall' );
        Route::get( 'remove-supervisor/{ccid}/{sid}', 'MallsController@removeSupervisor' )->name( 'remove-supervisor' );
        Route::get( 'export', 'MallsController@export' )->name( 'export-malls' );

        Route::get( 'new', 'MallsController@new' )->name( 'add-mall' );
        Route::post( 'create', 'MallsController@create' )->name( 'create-mall' );

    }
);

Route::group(
    [
        'prefix'    => 'offers',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( '', 'OffersController@index' )->name( 'all-offers' );
        Route::post( '', 'OffersController@offersearch' )->name( 'offers-search' );

        Route::get( 'details/{id}', 'OffersController@details' )->name( 'offers-details' );

        Route::get( 'status/{id}/{status}', 'OffersController@status' )->name( 'offer-status' );
        Route::get( 'cancel/{id}/{status}', 'OffersController@cancel' )->name( 'offer-cancel' );

        Route::get( 'edit/{id}', 'OffersController@edit' )->name( 'edit-offer' );
        Route::post( 'update', 'OffersController@update' )->name( 'update-offer' );
        Route::get( 'export', 'OffersController@export' )->name( 'export-offers' );

        Route::get( 'upload-image/{id}', 'OffersController@uploadImage' )->name( 'offer-upload-image' );
        Route::post( 'save-image', 'OffersController@saveImage' )->name( 'offer-save-image' );
    }
);

Route::group(
    [
        'prefix'    => 'centers',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( '', 'CCentersController@index' )->name( 'all-centers' );
        Route::get( 'details/{id}', 'CCentersController@details' )->name( 'center-details' );
        Route::get( 'edit/{id}', 'CCentersController@edit' )->name( 'edit-center' );
        Route::get( 'delete/{id}', 'CCentersController@delete' )->name( 'delete-center' );
        Route::post( 'update', 'CCentersController@update' )->name( 'update-center' );
        Route::get( 'new', 'CCentersController@new' )->name( 'add-center' );
        Route::post( 'create', 'CCentersController@create' )->name( 'create-center' );
        Route::get( 'export', 'CCentersController@export' )->name( 'export-centers' );
    }
);

app/Http/Controllers/CCentersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AddCCenterRequest;
use App\Http\Requests\EditCCenterRequest;
use App\Models\Catena;
use App\Models\CentroCommerciale;
use App\Models\Supervisor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Shop;

class CCentersController extends Controller {
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {

        $ccenters = CentroCommerciale::paginate( config('constants.options.options_pagination') );

        return view( 'ccenters.list', compact(  'ccenters' ) );

    }

    public function details( $id ) {

        $ccenter = CentroCommerciale::withCount( 'shops' )->findOrFail( $id );

        return view( 'ccenters.details', compact( 'ccenter' ) );
    }

    /**
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function edit( $id ) {
        $ccenter = CentroCommerciale::findOrFail( $id );

        return view('ccenters.forms.edit-ccenter', compact( 'ccenter' ) );
    }

    /**
     *
     * @param EditCCenterRequest $request
     * @return \Illuminate\Http\Response
     */
    public function update( EditCCenterRequest $request ) {

        $fields = $request->all();

        $ccenter = CentroCommerciale::findOrFail( $fields[ 'mall_id' ] );


        try { // tenta l'inserimento

            // inizializza un transazione
            DB::beginTransaction();

            $ccenter->cc_name       = $fields[ 'cc_name' ];

            $ccenter->save();

            // committa la transazione
            DB::commit();

            session()->flash( 'success', __('labels.ccenter_edit_page.edit_ok' ) );
            return redirect()->route( 'center-details', [ 'id' => $ccenter->id ] );

        } catch ( \Exception $e ) { // se genera eccezione

            // esegue un rollback sulla transazione
            DB::rollBack();

            session()->flash( 'error', __('labels.ccenter_edit_page.edit_ko' ) );
            return redirect()->route( 'center-details', [ 'id' => $ccenter->id ] );

        }
    }

    /**
     *
     * @return \Illuminate\Http\Response
     */
    public function new() {

        return view('ccenters.forms.add-ccenter' );
    }

    /**
     *
     * @param AddCCenterRequest $request
     * @return \Illuminate\Http\Response
     */
    public function create( AddCCenterRequest $request ) {

        $fields = $request->all();

        try { // tenta l'inserimento

            // inizializza un transazione
            DB::beginTransaction();

            $ccenter = new CentroCommerciale();

            $ccenter->cc_name = $fields[ 'cc_name' ];
            $ccenter->save();

            // committa la transazione
            DB::commit();

            session()->flash( 'success', __('labels.ccenter_add_page.add_ok' ) );
            return redirect()->route( 'center-details', [ 'id' => $ccenter->id ] );

        } catch ( \Exception $e ) { // se genera eccezione

            // esegue un rollback sulla transazione
            DB::rollBack();

            session()->flash( 'error', __('labels.ccenter_add_page.add_ko' ) );
            return redirect()->route( 'all-centers' );

        }

    }

    public function delete( $id ) {

        try { // tenta la rimozione

            $ccenter = CentroCommerciale::findOrFail( $id );

            // inizializza una transazione
            DB::beginTransaction();

            Shop::where( [ 's_centro_commerciale_ext' => $id ] )->update(['s_centro_commerciale_ext' => null]);

            $ccenter->delete();

            // committa la transazione
            DB::commit();

            session()->flash( 'success', __('labels.ccenter_deletion.deletion_ok' ) );
            return redirect()->route( 'all-centers' );

        } catch ( \Exception $e ) { // se genera eccezione

            // esegue un rollback sulla transazione
            DB::rollBack();

            session()->flash( 'error', __('labels.ccenter_deletion.deletion_ko' ) );
            return redirect()->route( 'center-details', [ 'id' => $id ] );

        }
    }

    public function export($dieScript = true){
        $records = CentroCommerciale::get();
        $csvExporter = new \Laracsv\Export();
        $csvExporter->beforeEach( function ( $record ) {
            $record->parsed_created_at = date( 'd/m/Y H:i:s', $record->created_at );
            $record->parsed_updated_at = date( 'd/m/Y H:i:s', $record->updated_at );
        } );

        $columns = [
            'id',
            'cc_name',
            'parsed_created_at',
            'parsed_updated_at',
        ];

        $csvExporter->build( $records, $columns )->download('centricommerciali.csv' );

       if ($dieScript) exit();
    }

}

resources/views/ccenters/details.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include( 'ui.messages' )
    <div class="row justify-content-center">
        <div class="col-md-12 col-lg-10">
            <div class="card">
                <div class="card-header">
                    <h4 class="text-center m-0">
                        @lang( 'labels.ccenter_details_title' ) "{{ $ccenter->cc_name }}"
                    </h4>
                </div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <div class="row">
                                <div class="col">
                                    <strong>
                                        @lang( 'labels.ccenter_details_page.ccenter_name' )
                                    </strong>
                                </div>
                                <div class="col">
                                    {{ $ccenter->cc_name }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <strong>
                                        @lang( 'labels.ccenter_details_page.shop_count' )
                                    </strong>
                                </div>
                                <div class="col">
                                    {{ $ccenter->shops_count }}
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="row">
                                <div class="col">
                                    <strong>
                                        @lang( 'labels.ccenter_details_page.created_at' )
                                    </strong>
                                </div>
                                <div class="col">
                                    {{ date( 'd-m-Y H:i:s', $ccenter->created_at ) }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <strong>
                                        @lang( 'labels.ccenter_details_page.updated_at' )
                                    </strong>
                                </div>
                                <div class="col">
                                    {{ date( 'd-m-Y H:i:s', $ccenter->updated_at ) }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card-footer text-center">

                    <a href="{{ route( 'edit-center', [ 'id' => $ccenter->id ] ) }}" class="btn btn-primary">
                        @lang( 'labels.ccenter_details_page.actions.edit_ccenter' )
                    </a>
                    <button type="button" class="btn btn-danger mb-1" data-toggle="modal" data-target="#deleteDataModal">
                        @lang( 'labels.ccenter_details_page.actions.delete_ccenter' )
                    </button>

                    <div class="modal fade" id="deleteDataModal" tabindex="-1" role="dialog" aria-labelledby="deleteDataModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <div class="col-12 text-center">
                                        <h5 class="modal-title text-center" id="deleteDataModalLabel">
                                            @lang( 'labels.ccenter_deletion.deletion_title', [ 'ccenter_name' => $ccenter->cc_name  ] )
                                        </h5>
                                    </div>
                                </div>

                                <div class="modal-body">
                                    @lang( 'labels.ccenter_deletion.deletion_alert' )
                                </div>
                                <div class="modal-footer">
                                    <div class="col-12 text-center">
                                        <a href="{{ route( 'delete-center', [ 'id' => $ccenter->id ] ) }}" class="btn btn-primary">
                                            @lang( 'labels.ccenter_deletion.deletion_confirm' )
                                        </a>
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <a href="{{ route( 'all-shops-centrocommerciale', [ 'ccid' => $ccenter->id ] ) }}" class="btn btn-primary">
                        @lang( 'labels.mall_details_page.actions.display_linked_shops' )
                    </a>
                    <a href="{{ route( 'all-centers' ) }}" class="btn btn-primary">
                        @lang( 'labels.back_to_list_label' )
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/ccenters/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h4 class="text-center m-0">
                            @lang( 'labels.ccenters_list_title' )
                        </h4>
                    </div>
                    <div class="">
                        <a href="{{ route( 'export-centers') }}" class="text-center list-group-item list-group-item-action bg-warning">
                            <i class="fa fa-file-download"></i>EXPORT CSV
                        </a>
                    </div>
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <div class="list-group">
                            @foreach( $ccenters as $c => $ccenter )
                                <a href="{{ route( 'center-details', [ 'id' => $ccenter->id ] ) }}" class="text-center list-group-item list-group-item-action">
                                    {{ $ccenter->cc_name }}
                                </a>
                            @endforeach
                        </div>

                        <div class="row mt-2">
                            <div class="col text-center">
                                {{ $ccenters->appends(request()->query())->links() }}
                            </div>
                        </div>
                    </div>

                    <div class="card-footer text-center">
                        <a href="{{ route( 'add-center' ) }}" class="btn btn-primary">
                            @lang( 'labels.ccenter_add_new' )
                        </a>
                        <a href="{{ route( 'home' ) }}" class="btn btn-primary">
                            @lang( 'labels.back_to_home_label' )
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection