routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get( '/home', 'HomeController@index' )->middleware( [ '\App\Http\Middleware\CheckAdmin' ] )->name( 'home' );

Route::get( '/db_backup', 'AdminsController@download_backup' )->middleware( [ '\App\Http\Middleware\CheckAdmin' ] )->name( 'db_backup' );
Route::get( '/db_partial_backup_csv', 'AdminsController@download_partial_backup_csv' )->middleware( [ '\App\Http\Middleware\CheckAdmin' ] )->name( 'db_partial_backup_csv' );


Route::group(
    [
        'prefix'    => 'users',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( 'administrators', 'UsersController@administrators' )->name( 'administrators' );
        Route::get( 'customers', 'UsersController@customers' )->name( 'customers' );
        Route::post( 'customers', 'UsersController@customersearch' )->name( 'customers-search' );
        Route::get( 'supervisors', 'UsersController@supervisors' )->name( 'supervisors' );
        Route::get( 'shop-owners', 'UsersController@commerciants' )->name( 'shop-owners' );
        Route::post( 'shop-owners', 'UsersController@commerciantsearch' )->name( 'commerciants-search' );
        Route::get( 'details/{id}', 'UsersController@details' )->name( 'user-details' );
        Route::get( 'status/{id}/{status}', 'UsersController@status' )->name( 'user-status' );
        Route::get( 'confirmed/{id}/{confirmed}', 'UsersController@confirmed' )->name( 'user-confirmed' );
        Route::get( 'delete-customer/{id}', 'UsersController@deleteCustomer' )->name( 'delete-customer' );
    }
);

Route::group(
    [
        'prefix'    => 'customers',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( 'favs/{id}', 'CustomersController@customerFavs' )->name( 'customer-favs' );
        Route::get( 'edit/{id}', 'CustomersController@edit' )->name( 'edit-customer' );
        Route::post( 'update', 'CustomersController@update' )->name( 'update-customer' );
        Route::get( 'export', 'CustomersController@export' )->name( 'export-customers' );
    }
);

Route::group(
    [
        'prefix'    => 'shop-owners',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( 'edit/{id}', 'CommerciantsController@edit' )->name( 'edit-shop-owner' );
        Route::post( 'update', 'CommerciantsController@update' )->name( 'update-shop-owner' );
        Route::get( 'offers-trade/{id}', 'CommerciantsController@offersTrade' )->name( 'offers-trade' );
        Route::post( 'offers-trade-save/', 'CommerciantsController@offersTradeSave' )->name( 'offers-trade-save' );
        Route::get( 'delete-all-data/{id}', 'CommerciantsController@deleteAllData' )->name( 'delete-shop-owner-data' );
        Route::get( 'export', 'CommerciantsController@export' )->name( 'export-shop-owner' );

    }
);

Route::group(
    [
        'prefix'    => 'supervisors',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( 'new', 'SupervisorsController@new' )->name( 'add-supervisor' );
        Route::post( 'create', 'SupervisorsController@create' )->name( 'create-supervisor' );
        Route::get( 'edit/{id}', 'SupervisorsController@edit' )->name( 'edit-supervisor' );
        Route::post( 'update', 'SupervisorsController@update' )->name( 'update-supervisor' );
        Route::get( 'remove-from-mall/{id}', 'SupervisorsController@removeFromMall' )->name( 'remove-from-mall' );
        Route::get( 'delete-all-data/{id}', 'SupervisorsController@deleteAllData' )->name( 'delete-supervisor-data' );
    }
);

Route::group(
    [
        'prefix'    => 'admins',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( 'new', 'AdminsController@new' )->name( 'add-admin' );
        Route::post( 'create', 'AdminsController@create' )->name( 'create-admin' );
        Route::get( 'edit/{id}', 'AdminsController@edit' )->name( 'edit-admin' );
        Route::post( 'update', 'AdminsController@update' )->name( 'update-admin' );

    }
);

Route::group(
    [
        'prefix'    => 'shops',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( '', 'ShopsController@index' )->name( 'all-shops' );
        Route::get( 'malls/{id}', 'ShopsController@catenacommerciale' )->name( 'all-shops-catenacommerciale' );
        Route::get( 'ccenters/{id}', 'ShopsController@centrocommerciale' )->name( 'all-shops-centrocommerciale' );
        Route::get( 'details/{id}', 'ShopsController@details' )->name( 'shop-details' );
        Route::get( 'status/{id}/{status}', 'ShopsController@status' )->name( 'shop-status' );
        Route::get( 'edit/{id}', 'ShopsController@edit' )->name( 'edit-shop' );
        Route::post( 'update', 'ShopsController@update' )->name( 'update-shop' );
        Route::get( 'offers/{id}', 'ShopsController@offers' )->name( 'shop-offers' );
        Route::get( 'export', 'ShopsController@export' )->name( 'export-shops' );

        Route::get( 'new', 'ShopsController@new' )->name( 'add-shop' );
        Route::post( 'create', 'ShopsController@create' )->name( 'create-shop' );

        Route::get( 'upload-image/{id}', 'ShopsController@uploadImage' )->name( 'shop-upload-image' );
        Route::post( 'save-image', 'ShopsController@saveImage' )->name( 'shop-save-image' );

        Route::get( 'delete-all-data/{id}', 'ShopsController@deleteAllData' )->name( 'delete-shop-data' );
    }
);

Route::group(
    [
        'prefix'    => 'malls', //CATENE COMMERCIALI
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( '', 'MallsController@index' )->name( 'all-malls' );
        Route::get( 'details/{id}', 'MallsController@details' )->name( 'mall-details' );
        Route::get( 'edit/{id}', 'MallsController@edit' )->name( 'edit-mall' );
        Route::get( 'delete/{id}', 'MallsController@delete' )->name( 'delete-mall' );
        Route::post( 'update', 'MallsController@update' )->name( 'update-mall' );
        Route::get( 'remove-supervisor/{ccid}/{sid}', 'MallsController@removeSupervisor' )->name( 'remove-supervisor' );
        Route::get( 'export', 'MallsController@export' )->name( 'export-malls' );

        Route::get( 'new', 'MallsController@new' )->name( 'add-mall' );
        Route::post( 'create', 'MallsController@create' )->name( 'create-mall' );

    }
);

Route::group(
    [
        'prefix'    => 'offers',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( '', 'OffersController@index' )->name( 'all-offers' );
        Route::post( '', 'OffersController@offersearch' )->name( 'offers-search' );

        Route::get( 'details/{id}', 'OffersController@details' )->name( 'offers-details' );

        Route::get( 'status/{id}/{status}', 'OffersController@status' )->name( 'offer-status' );
        Route::get( 'cancel/{id}/{status}', 'OffersController@cancel' )->name( 'offer-cancel' );

        Route::get( 'edit/{id}', 'OffersController@edit' )->name( 'edit-offer' );
        Route::post( 'update', 'OffersController@update' )->name( 'update-offer' );
        Route::get( 'export', 'OffersController@export' )->name( 'export-offers' );

        Route::get( 'upload-image/{id}', 'OffersController@uploadImage' )->name( 'offer-upload-image' );
        Route::post( 'save-image', 'OffersController@saveImage' )->name( 'offer-save-image' );
    }
);

Route::group(
    [
        'prefix'    => 'centers',
        // 'namespace' => 'App\Http\Controllers'
    ],
    function () {
        Route::get( '', 'CCentersController@index' )->name( 'all-centers' );
        Route::get( 'details/{id}', 'CCentersController@details' )->name( 'center-details' );
        Route::get( 'edit/{id}', 'CCentersController@edit' )->name( 'edit-center' );
        Route::get( 'delete/{id}', 'CCentersController@delete' )->name( 'delete-center' );
        Route::post( 'update', 'CCentersController@update' )->name( 'update-center' );
        Route::get( 'new', 'CCentersController@new' )->name( 'add-center' );
        Route::post( 'create', 'CCentersController@create' )->name( 'create-center' );
        Route::get( 'export', 'CCentersController@export' )->name( 'export-centers' );
    }
);

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Schema;


class Customer extends Model {

    protected $table = 'customer';
    protected $primaryKey = 'id'; // or null

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'u_name',
        'user_id',
        'u_last_name',
        'u_prov',
        'u_prov_code',
        'u_blocked',
        'u_confirmed',
        'u_token',
        'u_notification_ios_token',
        'u_notification_android_token',
        'u_notification_ios_on',
        'u_notification_android_on',
        'u_notification_provincia',
        'u_notification_only_filters',
        'u_notification_discounts',
        'u_notification_categories',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'created_at' => 'timestamp',
        'updated_at' => 'timestamp',
    ];

    public function user() {
        return $this->belongsTo('App\Models\User' );
    }

    public function favs() {
        return $this->belongsToMany('App\Models\Offer','user_favs', 'uf_userid_ext', 'uf_offerid_ext');
    }

    public function likedOffers() {
        return $this->belongsToMany('App\Models\Offer', 'users_likes','ul_userid_ext','ul_offerid_ext')->withTimestamps();
    }

    public function scopeByUserId( $query, $id ) {
        return $query->where( 'user_id', $id );
    }

    public function scopeNotBlocked( $query ) {
        return $query->where( 'u_blocked', '<>', 1 );
    }

    public function getBlockedLabelAttribute() {
        return $this->u_blocked === 0 ? 'NO' : 'SI';
    }

    public function getConfirmedLabelAttribute() {
        return $this->u_confirmed === 0 ? 'NO' : 'SI';
    }

    public static function getTableColumns() {
        return Schema::getColumnListing( 'customer' );
    }
}

app/Models/Shop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Shop extends Model {

    protected $table = 'shop';
    protected $primaryKey = 'id'; // or null

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        's_commerciant_ext',
        's_blocked',
        's_name',
        's_image_name',
        's_image',
        's_image_real_path',
        's_image_path',
        's_desc',
        's_prd',
        's_indirizzo',
        's_cap',
        's_city',
        's_prov',
        's_prov_code',
        's_lat',
        's_lon',
        's_cat',
        's_catena_commerciale_ext',
        's_centro_commerciale_ext',
        's_centro_commerciale_piano',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'created_at' => 'timestamp',
        'updated_at' => 'timestamp',
    ];

    /**
     * La Catena commerciale a cui appartiere lo shop
     */
    public function catena() {
        return $this->belongsTo('App\Models\Catena', 's_catena_commerciale_ext', 'id' );
    }

    /**
     * Il Centro commerciale dove si trova lo shop
     */
    public function centroCommerciale() {
        return $this->belongsTo('App\Models\CentroCommerciale', 's_centro_commerciale_ext', 'id' );
    }

    /**
     * Le Offerte dello Shop
     */
    public function offerte() {
        return $this->hasMany('App\Models\Offer', 'o_shop_ext', 'id' );
    }

    public function owner() {
        return $this->belongsTo('App\Models\Commerciant', 's_commerciant_ext', 'id' );
    }

    public function categoria() {
        return $this->belongsTo('App\Models\Category', 's_cat', 'id' );
    }

    public function scopeNotBlocked( $query ) {
        return $query->where( 's_blocked', '<>', 1 );
    }

    public function getBlockedLabelAttribute() {
        return $this->s_blocked === 0 ? 'NO' : 'SI';
    }

    public static function getTableColumns() {
    list($cols, $values) = array_divide((new static)->first()->toArray());
    return $cols;
}
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Models\Commerciant;

class User extends Authenticatable {
    use Notifiable;

    const ADMINISTRATOR = 1;
    const CUSTOMER = 2;
    const COMMERCIANT = 3;
    const SUPERVISOR = 4;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'fullname', 'email', 'password', 'type_id', 'activation_token', 'api_password_reset_token', 'logged'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'logged'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'created_at'        => 'timestamp',
        'updated_at'        => 'timestamp',
        'email_verified_at' => 'timestamp',
    ];

    public function scopeByTypeId( $query, $id ) {
        return $query->where( 'type_id', $id );
    }

    public function commerciant() {
        return $this->hasOne('App\Models\Commerciant');
    }

    public static function getTableColumns() {
        list($cols, $values) = array_divide((new static)->first()->toArray());
        return $cols;
    }
}

resources/views/users/details-partials/actions-admin.blade.php
<a href="{{ route( 'edit-admin', [ 'id' => $data->id ] ) }}" class="btn btn-primary">
    @lang( 'labels.user_details_page.actions.edit_admin' )
</a>

resources/views/users/details-partials/actions-commerciant.blade.php
@if( $data->c_blocked === 0 )
    <a href="{{ route( 'user-status', [ 'id' => $data->user_id, 'status' => 1 ] ) }}" class="btn btn-danger mb-1">
        @lang( 'labels.user_details_page.actions.block_action' )
    </a>
@else
    <a href="{{ route( 'user-status', [ 'id' => $data->user_id, 'status' => 0 ] ) }}" class="btn btn-warning mb-1">
        @lang( 'labels.user_details_page.actions.unblock_action' )
    </a>
@endif

@if( $data->c_confirmed === 0 )
    <a href="{{ route( 'user-confirmed', [ 'id' => $data->user_id, 'confirmed' => 1 ] ) }}" class="btn btn-success mb-1">
        @lang( 'labels.user_details_page.actions.confirm_action' )
    </a>
@else
    <a href="{{ route( 'user-confirmed', [ 'id' => $data->user_id, 'confirmed' => 0 ] ) }}" class="btn btn-warning mb-1">
        @lang( 'labels.user_details_page.actions.unconfirm_action' )
    </a>
@endif

<a href="{{ route( 'edit-shop-owner', [ 'id' => $data->user_id ] ) }}" class="btn btn-primary mb-1">
    @lang( 'labels.user_details_page.actions.edit_commerciant' )
</a>

<a href="{{ route( 'shop-details', [ 'id' => $data->shop->id ] ) }}" class="btn btn-primary mb-1">
    @lang( 'labels.user_details_page.actions.view_shop' )
</a>

<a href="{{ route( 'offers-trade', [ 'id' => $data->id ] ) }}" style="display: none" class="btn btn-primary mb-1">
    @lang( 'labels.user_details_page.actions.offers_trade' )
</a>


<button type="button" class="btn btn-danger mb-1" data-toggle="modal" data-target="#deleteDataModal">
    Cancella tutti i dati
</button>

<div class="modal fade" id="deleteDataModal" tabindex="-1" role="dialog" aria-labelledby="deleteDataModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <div class="col-12 text-center">
                    <h5 class="modal-title text-center" id="deleteDataModalLabel">
                        @lang( 'labels.user_details_page.actions.delete_commerciant_title', [ 'commerciant_name' => $data->c_name . ' ' . $data->c_last_name  ] )
                    </h5>
                </div>
            </div>

            <div class="modal-body">
                @lang( 'labels.user_details_page.actions.delete_commerciant_alert' )
            </div>
            <div class="modal-footer">
                <div class="col-12 text-center">
                    <a href="{{ route( 'delete-shop-owner-data', [ 'id' => $data->id ] ) }}" class="btn btn-primary">
                        @lang( 'labels.user_details_page.actions.confirm_commerciant_deletion' )
                    </a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/users/details-partials/actions-customer.blade.php
@if( $data->u_blocked === 0 )
    <a href="{{ route( 'user-status', [ 'id' => $data->user_id, 'status' => 1 ] ) }}" class="btn btn-danger">
        @lang( 'labels.user_details_page.actions.block_action' )
    </a>
@else
    <a href="{{ route( 'user-status', [ 'id' => $data->user_id, 'status' => 0 ] ) }}" class="btn btn-warning">
        @lang( 'labels.user_details_page.actions.unblock_action' )
    </a>
@endif

@if( $data->u_confirmed === 0 )
    <a href="{{ route( 'user-confirmed', [ 'id' => $data->user_id, 'confirmed' => 1 ] ) }}" class="btn btn-success">
        @lang( 'labels.user_details_page.actions.confirm_action' )
    </a>
@else
    <a href="{{ route( 'user-confirmed', [ 'id' => $data->user_id, 'confirmed' => 0 ] ) }}" class="btn btn-warning">
        @lang( 'labels.user_details_page.actions.unconfirm_action' )
    </a>
@endif

<a href="{{ route( 'edit-customer', [ 'id' => $data->user_id ] ) }}" class="btn btn-primary">
    @lang( 'labels.user_details_page.actions.edit_customer' )
</a>

<a href="{{ route( 'customer-favs', [ 'id' => $data->user_id ] ) }}" class="btn btn-primary">
    @lang( 'labels.user_details_page.actions.customer_favs' )
</a>

<button type="button" class="btn btn-danger mb-1" data-toggle="modal" data-target="#deleteDataModal">
    Cancella tutti i dati
</button>
<div class="modal fade" id="deleteDataModal" tabindex="-1" role="dialog" aria-labelledby="deleteDataModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <div class="col-12 text-center">
                    <h5 class="modal-title text-center" id="deleteDataModalLabel">
                        @lang( 'labels.consumer_deletion.delete_consumer_title', [ 'consumer_name' => $data->u_name  . " ".$data->u_last_name] )
                    </h5>
                </div>
            </div>

            <div class="modal-body">
                @lang( 'labels.consumer_deletion.delete_consumer_alert' )
            </div>
            <div class="modal-footer">
                <div class="col-12 text-center">
                    <a href="{{ route( 'delete-customer', [ 'id' => $data->user_id ] ) }}" class="btn btn-primary">
                        @lang( 'labels.consumer_deletion.confirm_consumer_deletion' )
                    </a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/users/details-partials/actions-supervisor.blade.php
@if( $data->ccs_blocked === 0 )
    <a href="{{ route( 'user-status', [ 'id' => $data->user_id, 'status' => 1 ] ) }}" class="btn btn-danger mb-1">
        @lang( 'labels.user_details_page.actions.block_action' )
    </a>
@else
    <a href="{{ route( 'user-status', [ 'id' => $data->user_id, 'status' => 0 ] ) }}" class="btn btn-warning mb-1">
        @lang( 'labels.user_details_page.actions.unblock_action' )
    </a>
@endif

<a href="{{ route( 'edit-supervisor', [ 'id' => $data->user_id ] ) }}" class="btn btn-primary mb-1">
    @lang( 'labels.user_details_page.actions.edit_supervisor' )
</a>

@if( $data->catena )
    <a href="{{ route( 'mall-details', [ 'id' => $data->catena->id ] ) }}" class="btn btn-primary mb-1">
        @lang( 'labels.user_details_page.actions.view_mall' )
    </a>
@endif

<button type="button" class="btn btn-danger mb-1" data-toggle="modal" data-target="#deleteDataModal">
    Cancella tutti i dati
</button>
<div class="modal fade" id="deleteDataModal" tabindex="-1" role="dialog" aria-labelledby="deleteDataModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <div class="col-12 text-center">
                    <h5 class="modal-title text-center" id="deleteDataModalLabel">
                        @lang( 'labels.supervisor_deletion.delete_supervisor_title', [ 'supervisor_name' => $data->ccs_name  . " ".$data->ccs_last_name] )
                    </h5>
                </div>
            </div>

            <div class="modal-body">
                @lang( 'labels.supervisor_deletion.delete_supervisor_alert' )
            </div>
            <div class="modal-footer">
                <div class="col-12 text-center">
                    <a href="{{ route( 'delete-supervisor-data', [ 'id' => $data->id ] ) }}" class="btn btn-primary">
                        @lang( 'labels.supervisor_deletion.confirm_supervisor_deletion' )
                    </a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/users/details-partials/details-administrator.blade.php
ADMIN DETAILS

resources/views/users/details-partials/details-commerciant.blade.php
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.first_name' )
        </strong>
    </div>
    <div class="col">
        {{ $data->c_name }}
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.last_name' )
        </strong>
    </div>
    <div class="col">
        {{ $data->c_last_name }}
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.blocked' )
        </strong>
    </div>
    <div class="col">
        {{ $data->blocked_label }}
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.confirmed' )
        </strong>
    </div>
    <div class="col">
        {{ $data->confirmed_label }}
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.token' )
        </strong>
    </div>
    <div class="col">
        {{ $data->c_token }}
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.sub_expiration' )
        </strong>
    </div>
    <div class="col">
        {{ is_null($data->c_subscription) ? __('labels.user_details_page.expiration_null') : date( 'd-m-Y H:i:s', $data->c_subscription ) }}
    </div>
</div>

resources/views/users/details-partials/details-customer.blade.php
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.first_name' )
        </strong>
    </div>
    <div class="col">
        {{ $data->u_name }}
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.last_name' )
        </strong>
    </div>
    <div class="col">
        {{ $data->u_last_name }}
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.prov' )
        </strong>
    </div>
    <div class="col">
        {{ $data->u_prov }} - {{ $data->u_prov_code }}
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.blocked' )
        </strong>
    </div>
    <div class="col">
        <p class="{{ $data->blocked_label == "NO" ? "" : "bg-danger" }}">{{ $data->blocked_label }}</p>
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.confirmed' )
        </strong>
    </div>
    <div class="col">
        {{ $data->confirmed_label }}
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.token' )
        </strong>
    </div>
    <div class="col">
        {{ $data->u_token }}
    </div>
</div>

resources/views/users/details-partials/details-supervisor.blade.php
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.first_name' )
        </strong>
    </div>
    <div class="col">
        {{ $data->ccs_name }}
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.last_name' )
        </strong>
    </div>
    <div class="col">
        {{ $data->ccs_last_name }}
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.blocked' )
        </strong>
    </div>
    <div class="col">
        {{ $data->blocked_label }}
    </div>
</div>
<div class="row">
    <div class="col">
        <strong>
            @lang( 'labels.user_details_page.cc_ext' )
        </strong>
    </div>
    <div class="col">
        @if ($data->catena)
            <a href="{{ route( 'mall-details', [ 'id' => $data->catena->id ] ) }}">
                {{ $data->catena ? $data->catena->cc_name : '------' }}
            </a>
        @else
            {{ $data->catena ? $data->catena->cc_name : '------' }}
        @endif


    </div>
</div>